### ISSUE TITLE
Can't import and build

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlesamples/android-vulkan-tutorials#50]
I get this, for example, when trying tutorial06 :

![image](https://user-images.githubusercontent.com/5357526/39408489-bb824a44-4bdf-11e8-94bb-c915332fb0d2.png)

**Comment by AndroidDeveloperLB** [comment]
Why not change the repo to have it ready for others to import and build right away?
Can you please fix this issue in the repo somehow?

Anyway, I tried what you wrote, and I still got an error:

![image](https://user-images.githubusercontent.com/5357526/39509821-481a7d5c-4df0-11e8-963f-37552f2c8f3d.png)

**Comment by ggfan** [comment]
this should be fixed now.  Thanks!

**Comment by AndroidDeveloperLB** [comment]
Still doesn't work. Why close it?

This is again the same issue:
![image](https://user-images.githubusercontent.com/5357526/39538955-15d5473a-4e47-11e8-9b4f-5a740a3409b4.png)

BTW, speaking of this sample, some links do not work here:
https://github.com/googlesamples/android-vulkan-tutorials/tree/master/tutorial06_texture
Meaning this:
https://github.com/github.com/google/cdep
